name: mad
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1  # Add Google Fonts package
  flutter_svg: ^2.0.14
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  http: ^1.2.2
  imgbb_uploader: ^0.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/   # Includes all files under the assets directory
  