// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKw4NnICB3eeyY-QGhyZbQK6j2O72OYmI',
    appId: '1:455035774982:web:d0931f8b84839dafc9bb87',
    messagingSenderId: '455035774982',
    projectId: 'com-abnaseer-mad',
    authDomain: 'com-abnaseer-mad.firebaseapp.com',
    storageBucket: 'com-abnaseer-mad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt1MmMgP8FCQDf2sJNWof7JA5IX1RiRHs',
    appId: '1:455035774982:android:37e1459fc3219675c9bb87',
    messagingSenderId: '455035774982',
    projectId: 'com-abnaseer-mad',
    storageBucket: 'com-abnaseer-mad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7kxYdpP8-12uI6-IN7x8i2s_YMLquNVQ',
    appId: '1:455035774982:ios:bdea168ed72b08d7c9bb87',
    messagingSenderId: '455035774982',
    projectId: 'com-abnaseer-mad',
    storageBucket: 'com-abnaseer-mad.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtWELbS0on4_t4Ivf14Yk9yrMOOOq9grM',
    appId: '1:1096656087748:ios:f154eaae315d44a83af791',
    messagingSenderId: '1096656087748',
    projectId: 'abnaseer-mad',
    storageBucket: 'abnaseer-mad.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV0Qy8-_VVe18YdAUH_tm7iBkSEB6yUd4',
    appId: '1:1096656087748:web:a606c20580b386ba3af791',
    messagingSenderId: '1096656087748',
    projectId: 'abnaseer-mad',
    authDomain: 'abnaseer-mad.firebaseapp.com',
    storageBucket: 'abnaseer-mad.firebasestorage.app',
    measurementId: 'G-MY61RPDZQQ',
  );
}